name: CICD sanket bhaiya backend class

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: // multiple version of one lang
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2 // checks out the code
      - name: Use node js
        uses: actions/setup-node@v1  // sets the node version
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install

        env: 
          CI: true   


